-- CREATE TABLE users(id SERIAL PRIMARY KEY,
--     username VARCHAR(20) NOT NULL UNIQUE,
--     first_name VARCHAR(20) NOT NULL,
--     last_name VARCHAR(20) NOT NULL,
--     password VARCHAR(255) NOT NULL);